<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Canteen Sales Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            color: #333;
        }

        .header {
            text-align: center;
            padding: 10px 0;
            border-bottom: 2px solid #ddd;
        }

        .header h1 {
            font-size: 24px;
            margin: 5px 0;
        }

        .header h2 {
            font-size: 18px;
            margin: 0;
            color: #555;
        }

        .details {
            margin: 20px;
            font-size: 14px;
        }

        .details p {
            margin: 5px 0;
        }

        .details .strong {
            font-weight: bold;
        }

        .report-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        .report-table th,
        .report-table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .report-table th {
            background-color: #f4f4f4;
            font-size: 14px;
            font-weight: bold;
        }

        .report-table tbody tr:hover {
            background-color: #f9f9f9;
        }

        .footer {
            text-align: right;
            font-size: 12px;
            margin: 20px;
            border-top: 1px solid #ddd;
            padding-top: 10px;
            color: #777;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>Midlands State University</h1>
        <h2>Canteen Sales Report</h2>
    </div>

    <div class="details">
        <p><span class="strong">Report Date Range:</span> {{ $start_date ?? 'N/A' }} - {{ $end_date ?? 'N/A' }}</p>
        <p><span class="strong">Generated By:</span> {{ $generated_by }}</p>
        <p><span class="strong">Date Generated:</span> {{ date('Y-m-d H:i:s') }}</p>
    </div>

    <table class="report-table">
        <thead>
            <tr>
                <th>Reference</th>
                <th>Amount</th>
                <th>Currency</th>
                <th>Type</th>
                <th>Cashier</th>
                <th>Created At</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($sales as $sale)
                <tr>
                    <td>{{ $sale->reference }}</td>
                    <td>${{ number_format($sale->amount, 2) }}</td>
                    <td>{{ $sale->currency }}</td>
                    <td>{{ $sale->type }}</td>
                    <td>{{ $sale->name }}</td>
                    <td>{{ $sale->created_at }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Midlands State University Canteen System</p>
    </div>
</body>
</html>
